OLED_ENABLE = yes
OLED_TRANSPORT = i2c
OLED_DRIVER = ssd1306

RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
# required for rp2040
LTO_ENABLE = yes

JOYSTICK_ENABLE = yes

BOARD = GENERIC_RP_RP2040