#define ENCODER_A_PINS { GP14 }
#define ENCODER_B_PINS { GP15 }

#define WS2812_DI_PIN GP3

#define I2C_DRIVER I2CD1
#define I2C1_SDA_PIN GP16
#define I2C1_SCL_PIN GP17

#define JOYSTICK_BUTTON_COUNT 0
#define JOYSTICK_AXIS_COUNT 2
#define JOYSTICK_AXIS_RESOLUTION 12